# Generated by Django 5.2.7 on 2026-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0006_alter_aboutmeconfiguration_profile_image_and_more'),
    ]

    operations = [
        # Delete Spotify models - delete dependent models first, then parents
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
        migrations.DeleteModel(
            name='SpotifyTrack',
        ),
        migrations.DeleteModel(
            name='SpotifyPlaylist',
        ),
        # Remove spotify_url from ManualTrack
        migrations.RemoveField(
            model_name='manualtrack',
            name='spotify_url',
        ),
        # Alter remaining fields
        migrations.AlterField(
            model_name='manualplaylist',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='manualplaylist',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='manualtrack',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this resource should be displayed'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Display this resource prominently'),
        ),
    ]
