# Generated by Django 5.2.7 on 2026-02-17 19:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0007_remove_spotifytrack_playlist_delete_spotifytoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(help_text='Brief description of the resource with HTML support'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Brief description of this resource category with HTML support'),
        ),
    ]
