# Generated by Django 5.2.7 on 2026-02-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_achievement_image_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'ACH'}, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.ForeignKey(limit_choices_to={'category_type': 'EXP'}, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Display this skill prominently on the home page'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'SKL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category'),
        ),
    ]
