# Generated by Django 5.2.7 on 2026-02-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_achievement_category_alter_category_slug_and_more'),
    ]

    operations = [
        # Rename fields to preserve existing data
        migrations.RenameField(
            model_name='project',
            old_name='youtube_url',
            new_name='youtube_embed_code',
        ),
        migrations.AlterField(
            model_name='project',
            name='youtube_embed_code',
            field=models.TextField(blank=True, default='', help_text='Paste the full YouTube iframe embed code or a plain YouTube URL. Example: <iframe src="https://www.youtube.com/embed/VIDEO_ID" ...></iframe>'),
        ),
        migrations.RenameField(
            model_name='videoresume',
            old_name='youtube_embed_url',
            new_name='embed_code',
        ),
        migrations.AlterField(
            model_name='videoresume',
            name='embed_code',
            field=models.TextField(blank=True, default='', help_text='Paste the full YouTube iframe embed code from YouTube\'s Share > Embed button, or a plain YouTube URL. Example: <iframe src="https://www.youtube.com/embed/VIDEO_ID" ...></iframe>'),
        ),
    ]
