# Generated by Django 5.2.7 on 2026-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_admin', 'Sent to Admin'), ('thankyou_sent', 'Thank You Sent'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
